/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.openjfx.dental.clinic.form.submission.java.application;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static org.openjfx.dental.clinic.form.submission.java.application.login_frm_patient.driver;
import static org.openjfx.dental.clinic.form.submission.java.application.login_frm_patient.password;
import static org.openjfx.dental.clinic.form.submission.java.application.login_frm_patient.url;
import static org.openjfx.dental.clinic.form.submission.java.application.login_frm_patient.username;

/**
 *
 * @author User
 */
public class creat_acc_form extends javax.swing.JFrame {

    /**
     * Creates new form creat_acc_form
     */
    public creat_acc_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernametxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JPasswordField();
        createaccbtn = new javax.swing.JButton();
        patientbtn = new javax.swing.JButton();
        employeebtn = new javax.swing.JButton();
        confirmpasswordtxt = new javax.swing.JPasswordField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 832));
        setMinimumSize(new java.awt.Dimension(1280, 832));
        setPreferredSize(new java.awt.Dimension(1280, 832));
        setResizable(false);
        getContentPane().setLayout(null);

        usernametxt.setBorder(null);
        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });
        getContentPane().add(usernametxt);
        usernametxt.setBounds(760, 265, 460, 30);

        passwordtxt.setBorder(null);
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });
        getContentPane().add(passwordtxt);
        passwordtxt.setBounds(760, 360, 460, 30);

        createaccbtn.setBackground(new java.awt.Color(0, 0, 0));
        createaccbtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        createaccbtn.setForeground(new java.awt.Color(255, 255, 255));
        createaccbtn.setText("Create Account");
        createaccbtn.setBorder(null);
        createaccbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaccbtnActionPerformed(evt);
            }
        });
        getContentPane().add(createaccbtn);
        createaccbtn.setBounds(857, 547, 239, 51);

        patientbtn.setBackground(new java.awt.Color(183, 247, 251));
        patientbtn.setText("Patient Login");
        patientbtn.setBorder(null);
        patientbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientbtn.setOpaque(true);
        patientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientbtnActionPerformed(evt);
            }
        });
        getContentPane().add(patientbtn);
        patientbtn.setBounds(799, 618, 355, 26);

        employeebtn.setBackground(new java.awt.Color(183, 247, 251));
        employeebtn.setText("Employee Login");
        employeebtn.setBorder(null);
        employeebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeebtn.setOpaque(true);
        employeebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeebtnActionPerformed(evt);
            }
        });
        getContentPane().add(employeebtn);
        employeebtn.setBounds(799, 644, 355, 26);

        confirmpasswordtxt.setBorder(null);
        confirmpasswordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpasswordtxtActionPerformed(evt);
            }
        });
        getContentPane().add(confirmpasswordtxt);
        confirmpasswordtxt.setBounds(760, 457, 460, 30);

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\dental-clinic-form-submission-java-application\\src\\dentalclinic-bg-frms\\creat-acc-frm.png")); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1280, 832);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtActionPerformed

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed

    private void createaccbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaccbtnActionPerformed
        // TODO add your handling code here:
        String usernameinput = usernametxt.getText();
        String passwordinput = new String (passwordtxt.getPassword());
        String confirmpasswordinput = new String (passwordtxt.getPassword());

        if (usernameinput.isEmpty() || passwordinput.isBlank() || confirmpasswordinput.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please fill in all the fields", "Dialog", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!passwordinput.equals(confirmpasswordinput)){
            JOptionPane.showMessageDialog(this, "Password Doesn't Match", "Dialog", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            try {
                Class.forName(driver);
                Connection con = DriverManager.getConnection(url, username, password);
                
                String sql = "INSERT INTO user (username, password,confirmpassword) VALUES (?,?,?)";
                PreparedStatement pst = con.prepareStatement(sql);
                
                pst.setString(1, usernameinput);
                pst.setString(2, passwordinput);
                pst.setString(3, confirmpasswordinput);
                
                int rowsInserted = pst.executeUpdate();
                if (rowsInserted>0){
                    JOptionPane.showMessageDialog(this,"Account Created Successfully");
                    login_frm_patient loginFrm = new login_frm_patient();
                    loginFrm.show();
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this,"Error in Creating Account. Try Again Later.");
                    return;
                }               
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_createaccbtnActionPerformed

    private void patientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientbtnActionPerformed
        // TODO add your handling code here:
        login_frm_patient LoginFrm = new login_frm_patient();
        LoginFrm.show();
        dispose();
    }//GEN-LAST:event_patientbtnActionPerformed

    private void employeebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeebtnActionPerformed
        // TODO add your handling code here:
        login_frm_employee LoginFrm = new login_frm_employee();
        LoginFrm.show();
        dispose();

    }//GEN-LAST:event_employeebtnActionPerformed

    private void confirmpasswordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpasswordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpasswordtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(creat_acc_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(creat_acc_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(creat_acc_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(creat_acc_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new creat_acc_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPasswordField confirmpasswordtxt;
    private javax.swing.JButton createaccbtn;
    private javax.swing.JButton employeebtn;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JButton patientbtn;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
