/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.openjfx.dental.clinic.form.submission.java.application;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static org.openjfx.dental.clinic.form.submission.java.application.login_frm_patient.driver;
import static org.openjfx.dental.clinic.form.submission.java.application.login_frm_patient.password;
import static org.openjfx.dental.clinic.form.submission.java.application.login_frm_patient.url;
import static org.openjfx.dental.clinic.form.submission.java.application.login_frm_patient.username;

/**
 *
 * @author User
 */
public class login_frm_employee extends javax.swing.JFrame {

    /**
     * Creates new form login_frm_employee
     */
    public login_frm_employee() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernametxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();
        createaccbtn = new javax.swing.JButton();
        patientbtn = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 832));
        setMinimumSize(new java.awt.Dimension(1280, 832));
        setResizable(false);
        getContentPane().setLayout(null);

        usernametxt.setBorder(null);
        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });
        getContentPane().add(usernametxt);
        usernametxt.setBounds(760, 265, 460, 30);

        passwordtxt.setBorder(null);
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });
        getContentPane().add(passwordtxt);
        passwordtxt.setBounds(760, 385, 460, 30);

        loginbtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn);
        loginbtn.setBounds(862, 476, 239, 51);

        createaccbtn.setBackground(new java.awt.Color(0, 0, 0));
        createaccbtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        createaccbtn.setForeground(new java.awt.Color(255, 255, 255));
        createaccbtn.setText("Create Account");
        createaccbtn.setBorder(null);
        createaccbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaccbtnActionPerformed(evt);
            }
        });
        getContentPane().add(createaccbtn);
        createaccbtn.setBounds(742, 645, 480, 51);

        patientbtn.setBackground(new java.awt.Color(183, 247, 251));
        patientbtn.setText("Patient Login");
        patientbtn.setBorder(null);
        patientbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientbtn.setOpaque(true);
        patientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientbtnActionPerformed(evt);
            }
        });
        getContentPane().add(patientbtn);
        patientbtn.setBounds(868, 547, 233, 26);

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\dental-clinic-form-submission-java-application\\src\\dentalclinic-bg-frms\\login-frm-employee.png")); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1280, 832);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        // TODO add your handling code here:
            loginbtnActionPerformed(evt);       // TODO add your handling code here:

    }//GEN-LAST:event_usernametxtActionPerformed

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
            loginbtnActionPerformed(evt);       // TODO add your handling code here:

    }//GEN-LAST:event_passwordtxtActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        String usernameinput = usernametxt.getText();
        String passwordinput = new String(passwordtxt.getPassword());

        if (usernameinput.isEmpty() || passwordinput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username and password must not be empty", "Message", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);

            String sql = "SELECT * FROM accounts_employee WHERE username = ? AND password = ?";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, usernameinput);
            pst.setString(2, passwordinput);

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                employee_dashboard_frm employeeFrm = new employee_dashboard_frm();
                employeeFrm.show();
                dispose();

            } else {
                String message = "Account Does not Exist";
                String checkusername = "SELECT * FROM accounts_employee WHERE username=?";
                pst = con.prepareStatement(checkusername);
                pst.setString(1,usernameinput);
                rs = pst.executeQuery();
                if (rs.next()) {
                    message = "Incorrect Password or Username";
                }
                JOptionPane.showMessageDialog(this, message);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_loginbtnActionPerformed

    private void patientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientbtnActionPerformed
        // TODO add your handling code here:
       login_frm_patient LoginFrm = new login_frm_patient();
       LoginFrm.show();        
       dispose();    
    }//GEN-LAST:event_patientbtnActionPerformed

    private void createaccbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaccbtnActionPerformed
        // TODO add your handling code here:
       creat_acc_form createFrm = new creat_acc_form();
       createFrm.show();        
       dispose(); 
    }//GEN-LAST:event_createaccbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_frm_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_frm_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_frm_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_frm_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_frm_employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton createaccbtn;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JButton patientbtn;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
